### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/phase-3-nested-hash-iteration#2]
### Canvas Link

https://learning.flatironschool.com/courses/4543/pages/enumerables-iterating-over-nested-hashes?module_item_id=335874

### Concern

The link pointing to `#delete_if` yields a 404. The closest I could find is:

https://docs.ruby-lang.org/en/2.7.0/Hash.html#method-i-delete_if

### Suggested Changes

Update link to be https://docs.ruby-lang.org/en/2.7.0/Hash.html#method-i-delete_if

**Comment by NaincyKumariKnoldus** [comment]
Hello @bdenney Can I solve this please?

**Comment by bdenney** [comment]
It looks like this is still an issue

**Comment by NaincyKumariKnoldus** [comment]
Hello @bdenney Can I do this please?

**Comment by bdenney** [comment]
@NaincyKumariKnoldus the PR looks good to me! Not sure what protocol dictates here but I'm okay closing this assuming that PR gets pushed eventually :)

**Comment by ihollander** [comment]
Hi @bdenney and @NaincyKumariKnoldus - thanks for your work on this issue! The curriculum team is responsible for updating the labs and ensuring that Canvas is also updated accordingly, so we'll take it from here 😄 We review issues and make updates on a weekly basis so your feedback will be addressed in a timely manner. 

Any time you notice issues in the future, keep doing what you're doing - open an issue in Canvas with the relevant details, and (optionally) make a PR if you know how the issue can be resolved. We might not accept all PRs since we might need to come up with alternate solutions than what you propose, but feedback is always welcome.

Appreciate your help! 💙
